# fly.toml app configuration file generated for tetricks on 2024-04-12T15:44:01-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tetricks'
primary_region = 'gru'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
